language: go
go:
    - 1.x
    - master
matrix:
    allow_failures:
        - go: master
before_install:
    - sudo apt-get update
    - sudo apt-get install -yy lxc-dev libacl1-dev
    - curl https://glide.sh/get | sh
install: make
script: make check
